# Generated by Django 5.2.12 on 2026-04-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourtBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_id', models.CharField(max_length=10)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('customer', models.CharField(default='Khách', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'start'],
                'indexes': [models.Index(fields=['date', 'court'], name='booking_boo_date_f148cd_idx')],
            },
        ),
    ]
