# Generated by Django 5.2.12 on 2026-04-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_type', models.CharField(choices=[('badminton', 'Cầu lông'), ('pickleball', 'Pickleball')], max_length=20)),
                ('start_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('day_of_week', models.IntegerField(blank=True, help_text='0=Monday ... 6=Sunday, để trống = mọi ngày', null=True)),
                ('price_per_hour', models.IntegerField()),
                ('rule_type', models.CharField(choices=[('normal', 'Giờ thường'), ('peak', 'Cao điểm')], default='normal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['court_type', 'start_minute'],
            },
        ),
    ]
