# Generated by Django 5.2.12 on 2026-04-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtblock',
            name='pricing_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='courtblock',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
