# Generated by Django 5.2.12 on 2026-04-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_courtblock_pricing_factor_courtblock_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtblock',
            name='rule_type',
            field=models.CharField(choices=[('normal', 'Giờ thường'), ('peak', 'Cao điểm')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
