# Generated by Django 5.2.12 on 2026-04-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_courtblock_rule_type_alter_pricerule_day_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_type', models.CharField(choices=[('badminton', 'Cầu lông'), ('pickleball', 'Pickleball')], max_length=20)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('pricing_factor', models.FloatField(default=1.0)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='court_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courtblock',
            name='rule_type',
            field=models.CharField(choices=[('normal', 'Giờ thường'), ('peak', 'Cao điểm'), ('monthly', 'Thuê tháng')], default='normal', max_length=20),
        ),
    ]
