# Generated by Django 5.2.12 on 2026-04-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_monthlyrule_booking_court_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyrule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='monthlyrule',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='monthlyrule',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='monthlyrule',
            name='priority',
        ),
        migrations.AlterField(
            model_name='courtblock',
            name='total_price',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
