# Generated by Django 5.2.12 on 2026-04-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_monthlyrule_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtblock',
            name='court_id',
            field=models.IntegerField(),
        ),
    ]
