# Generated by Django 5.2.12 on 2026-04-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_courtblock_court_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_boo_date_f148cd_idx',
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'court_id'], name='booking_boo_date_538de2_idx'),
        ),
    ]
