# Generated by Django 5.2.12 on 2026-04-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_booking_booking_boo_date_f148cd_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=10)),
                ('court_id', models.IntegerField()),
                ('date', models.DateField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('customer', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('estimated_price', models.IntegerField(default=0)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'date'], name='booking_boo_status_a6521d_idx')],
            },
        ),
    ]
