# Generated by Django 5.2.12 on 2026-04-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_bookingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
