# Generated by Django 5.2.12 on 2026-04-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_booking_booked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
